"""Root-Aware Message-Passing Neural Network (MPNN) Discriminator for GAN Training.

This module implements the discriminator component of the adversarial structural estimator,
which classifies rooted k-ego subgraphs as real (from observed data) or fake (from
simulated data generated by the structural model).

The discriminator uses Graph Isomorphism Network (GIN) layers to achieve maximal
expressiveness among 1-WL message-passing neural networks, with spectral normalization
for training stability.

Key design choices:
    - GIN architecture: Maximally expressive for distinguishing graph structures (Xu et al., 2019)
    - 2-layer MPNN: Matches k=2 identification radius for linear-in-means model
    - Root readout: Preserves root-specific information (vs global pooling)
    - Spectral normalization: Constrains discriminator sensitivity for stable training

References:
    - Xu, Hu, Leskovec & Jegelka (2019). "How Powerful are Graph Neural Networks?"
      ICLR 2019.
    - Miyato et al. (2018). "Spectral Normalization for Generative Adversarial Networks."
      ICLR 2018.
    - Kaji, Manresa & Pouliot (2023). "An Adversarial Approach to Structural Estimation."
      Econometrica, 91(6), 2041-2063.
"""

from __future__ import annotations

import torch
from torch import Tensor, nn
from torch.nn import functional as F
from torch.nn.utils.parametrizations import spectral_norm
from torch_geometric.nn import GINConv


class RootedMPNNDiscriminator(nn.Module):
    """Root-aware discriminator over rooted k-ego attributed subgraphs using GIN layers.

    This discriminator processes batches of rooted ego-subgraphs and outputs real/fake
    classification logits. Each node in the input has 3 features:
        [X_tilde, Y_tilde, root_marker]

    where:
        - X_tilde: Normalized covariate value
        - Y_tilde: Normalized outcome value
        - root_marker: Binary indicator (1.0 at root node, 0.0 elsewhere)

    Architecture:
        Input: Node features h_v^(0) = [X_tilde, Y_tilde, 1{v=root}], dim=3

        Layer 1: GINConv with MLP(3 → hidden → hidden)
                 → BatchNorm1d(hidden) → ReLU

        Layer 2: GINConv with MLP(hidden → hidden → hidden)
                 → BatchNorm1d(hidden) → ReLU

        Root readout: Extract h_root from aggregated embeddings

        Classification head: Linear(hidden → hidden) + spectral_norm → ReLU
                           → Linear(hidden → 1) + spectral_norm → logit

    The GIN layers use sum aggregation and trainable epsilon to maximize expressiveness
    on heterogeneous degree distributions (Barabási-Albert graphs).

    Args:
        hidden_dim: Hidden dimension for GIN layers and MLP head. Must be positive.
            Default: 64 (sufficient for 3-dim input on moderate-size subgraphs).
        logit_clip: Optional clipping bound for output logits. If provided, logits
            are clamped to [-logit_clip, +logit_clip] for bounded log-odds and
            stable loss computation. If None, no clipping is applied.
            Must be positive if specified. Default: None.

    Attributes:
        hidden_dim: Stored hidden dimension (int).
        logit_clip: Stored logit clipping bound or None (float | None).
        conv1: First GIN convolutional layer (GINConv).
        bn1: Batch normalization after first conv (BatchNorm1d).
        conv2: Second GIN convolutional layer (GINConv).
        bn2: Batch normalization after second conv (BatchNorm1d).
        head: Classification head with spectral-normalized linear layers (Sequential).

    Raises:
        ValueError: If hidden_dim <= 0 or logit_clip <= 0 when provided.

    Example:
        >>> import torch
        >>> from torch_geometric.data import Batch, Data
        >>>
        >>> # Create a batch of 2 rooted subgraphs
        >>> # Subgraph 1: 3 nodes, root at index 0
        >>> x1 = torch.randn(3, 3)  # [X_tilde, Y_tilde, root_marker]
        >>> x1[0, 2] = 1.0  # Mark root
        >>> edge1 = torch.tensor([[0, 1], [1, 0], [1, 2], [2, 1]], dtype=torch.long).t()
        >>> data1 = Data(x=x1, edge_index=edge1)
        >>>
        >>> # Subgraph 2: 4 nodes, root at index 0
        >>> x2 = torch.randn(4, 3)
        >>> x2[0, 2] = 1.0  # Mark root
        >>> edge2 = torch.tensor([[0, 1], [1, 0], [1, 2], [2, 1], [2, 3], [3, 2]],
        ...                       dtype=torch.long).t()
        >>> data2 = Data(x=x2, edge_index=edge2)
        >>>
        >>> # Create batch
        >>> batch = Batch.from_data_list([data1, data2])
        >>> root_indices = torch.tensor([0, 3], dtype=torch.long)  # 0 in subgraph 1, 0 in subgraph 2 (offset by 3)
        >>>
        >>> # Forward pass
        >>> disc = RootedMPNNDiscriminator(hidden_dim=64, logit_clip=10.0)
        >>> logits = disc(batch.x, batch.edge_index, root_indices)
        >>> print(logits.shape)  # (2,) - one logit per subgraph
        >>> probs = torch.sigmoid(logits)
        >>> print(probs)  # Probabilities of being "real"

    Notes:
        - Input batching: Uses PyG `Batch.from_data_list` convention where
          nodes and edges are concatenated, and `root_indices` indexes into
          the concatenated node array.
        - Root readout: Extracts node embeddings at `root_indices` positions
          after message passing, preserving root-specific information.
        - Spectral normalization: Applied to classification head layers (not to
          GIN layers) to constrain the discriminator's Lipschitz constant and
          stabilize adversarial training.
        - BatchNorm: Uses `track_running_stats=False` to compute batch-specific
          statistics during both training and evaluation, avoiding distribution
          shift issues in adversarial training.
        - Logit clipping: Optional boundedness prevents extreme logits from
          dominating loss while retaining smooth gradients everywhere.
        - Train epsilon: GIN epsilon parameter is trainable (`train_eps=True`)
          to adapt to degree heterogeneity in the graph.
    """

    def __init__(self, hidden_dim: int = 64, logit_clip: float | None = None) -> None:
        super().__init__()

        # Validate hyperparameters
        if hidden_dim <= 0:
            raise ValueError("hidden_dim must be positive.")
        if logit_clip is not None and logit_clip <= 0:
            raise ValueError("logit_clip must be positive when provided.")

        self.hidden_dim = int(hidden_dim)
        self.logit_clip = float(logit_clip) if logit_clip is not None else None

        # GIN Layer 1: 3-dim input → hidden_dim
        # MLP: Linear(3 → hidden) → ReLU → Linear(hidden → hidden)
        mlp1 = nn.Sequential(
            nn.Linear(3, self.hidden_dim),
            nn.ReLU(),
            nn.Linear(self.hidden_dim, self.hidden_dim),
        )
        self.conv1 = GINConv(mlp1, train_eps=True)
        # BatchNorm without running stats (batch-specific statistics)
        self.bn1 = nn.BatchNorm1d(self.hidden_dim, track_running_stats=False)

        # GIN Layer 2: hidden_dim → hidden_dim
        # MLP: Linear(hidden → hidden) → ReLU → Linear(hidden → hidden)
        mlp2 = nn.Sequential(
            nn.Linear(self.hidden_dim, self.hidden_dim),
            nn.ReLU(),
            nn.Linear(self.hidden_dim, self.hidden_dim),
        )
        self.conv2 = GINConv(mlp2, train_eps=True)
        self.bn2 = nn.BatchNorm1d(self.hidden_dim, track_running_stats=False)

        # Classification head with spectral normalization
        # Maps root embedding to a single logit
        self.head = nn.Sequential(
            spectral_norm(nn.Linear(self.hidden_dim, self.hidden_dim)),
            nn.ReLU(),
            spectral_norm(nn.Linear(self.hidden_dim, 1)),
        )

    def _validate_inputs(
        self, x: Tensor, edge_index: Tensor, root_indices: Tensor
    ) -> None:
        """Validate input tensors for forward pass.

        Args:
            x: Node feature matrix.
            edge_index: Edge connectivity in COO format.
            root_indices: Indices of root nodes in the batch.

        Raises:
            TypeError: If tensor types or dtypes are invalid.
            ValueError: If shapes or devices are incompatible.
        """
        # Validate node features x
        if not isinstance(x, Tensor):
            raise TypeError("x must be a torch.Tensor.")
        if x.ndim != 2 or x.shape[1] != 3:
            raise ValueError("x must have shape (num_nodes, 3).")
        if not torch.is_floating_point(x):
            raise TypeError("x must have a floating dtype.")

        # Validate edge_index
        if not isinstance(edge_index, Tensor):
            raise TypeError("edge_index must be a torch.Tensor.")
        if edge_index.dtype != torch.long:
            raise TypeError("edge_index must have dtype torch.long.")
        if edge_index.ndim != 2 or edge_index.shape[0] != 2:
            raise ValueError("edge_index must have shape (2, num_edges).")

        # Validate root_indices
        if not isinstance(root_indices, Tensor):
            raise TypeError("root_indices must be a torch.Tensor.")
        if root_indices.dtype != torch.long:
            raise TypeError("root_indices must have dtype torch.long.")
        if root_indices.ndim != 1:
            raise ValueError("root_indices must have shape (num_subgraphs,).")
        if root_indices.numel() == 0:
            raise ValueError("root_indices cannot be empty.")

        # Validate root_indices are within valid range
        if int(root_indices.min().item()) < 0 or int(root_indices.max().item()) >= x.shape[0]:
            raise ValueError("root_indices contain values outside valid node range.")

        # Validate all tensors are on same device
        if x.device != edge_index.device or x.device != root_indices.device:
            raise ValueError("x, edge_index, and root_indices must be on the same device.")

    def forward(self, x: Tensor, edge_index: Tensor, root_indices: Tensor) -> Tensor:
        """Classify rooted ego-subgraphs as real or fake.

        Processes node features through GIN layers with root-aware readout to
        produce classification logits for each subgraph in the batch.

        Args:
            x: Dense tensor of shape (num_nodes_in_batch, 3), floating dtype,
                representing concatenated node features across all subgraphs.
                Columns: [X_tilde, Y_tilde, root_marker].
                Must be on same device as edge_index and root_indices.
            edge_index: Long tensor of shape (2, num_edges_in_batch), representing
                edge connectivity in PyG COO format (concatenated across subgraphs
                with relabeled node indices). Must be on same device as x.
            root_indices: Long tensor of shape (num_subgraphs,), indexing the root
                node of each subgraph in the concatenated node array.
                Must be on same device as x.

        Returns:
            logits: Tensor of shape (num_subgraphs,), floating dtype, same device as x.
                Logits for real/fake classification. Positive values indicate "real",
                negative values indicate "fake". Pass through sigmoid for probabilities.
                If logit_clip is set, values are clamped to [-logit_clip, +logit_clip].

        Raises:
            TypeError: If input types or dtypes are invalid.
            ValueError: If shapes or devices are incompatible.

        Notes:
            - Message passing: Aggregates 2-hop neighborhood information at each node.
            - Root readout: Extracts embeddings at root_indices positions after MP.
            - Gradient flow: All operations are differentiable for adversarial training.
            - Logit clipping: Applied after head computation if logit_clip is not None.
        """
        self._validate_inputs(x=x, edge_index=edge_index, root_indices=root_indices)

        # Layer 1: GIN + BatchNorm + ReLU
        h = self.conv1(x, edge_index)
        h = F.relu(self.bn1(h))

        # Layer 2: GIN + BatchNorm + ReLU
        h = self.conv2(h, edge_index)
        h = F.relu(self.bn2(h))

        # Root readout: Extract embeddings at root positions
        root_h = h.index_select(0, root_indices)

        # Classification head: Map root embeddings to logits
        logits = self.head(root_h).squeeze(-1)

        # Optional logit clipping for bounded log-odds
        if self.logit_clip is not None:
            logits = logits.clamp(min=-self.logit_clip, max=self.logit_clip)

        return logits
